export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const TOGGLE_REFERENTIAL_TAXON_SELECTION = 'TOGGLE_REFERENTIAL_TAXON_SELECTION';
export const ACTIVATE_REFERENTIAL_TAXON_SELECTION_IN_BULK = 'ACTIVATE_REFERENTIAL_TAXON_SELECTION_IN_BULK';
