export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const TOGGLE_REFERENTIAL_TAXON = 'TOGGLE_REFERENTIAL_TAXON';
export const SELECT_MULTIPLE_REFERENTIAL_TAXA = 'SELECT_MULTIPLE_REFERENTIAL_TAXA';
