export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const TOGGLE_REFERENTIAL_TAXON_SELECTION = 'TOGGLE_REFERENTIAL_TAXON_SELECTION';
export const ACTIVATE_REFERENTIAL_TAXON_SELECTION_IN_BULK = 'ACTIVATE_REFERENTIAL_TAXON_SELECTION_IN_BULK';
export const TOGGLE_REFERENTIAL_TAXON_EXPANSION = 'TOGGLE_REFERENTIAL_TAXON_EXPANSION';
export const PERFORM_REFERENTIAL_TAXON_EXPANSION_IN_BULK = 'PERFORM_REFERENTIAL_TAXON_EXPANSION_IN_BULK';
export const TOGGLE_PERSONAL_TAXON_EXPANSION = 'TOGGLE_PERSONAL_TAXON_EXPANSION';
export const PERFORM_PERSONAL_TAXON_EXPANSION_IN_BULK = 'PERFORM_PERSONAL_TAXON_EXPANSION_IN_BULK';
